// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

/*
Package go_micro_srv_config_config is a generated protocol buffer package.

It is generated from these files:
	config/config.proto

It has these top-level messages:
	Change
	ChangeLog
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	SearchRequest
	SearchResponse
	WatchRequest
	WatchResponse
	AuditLogRequest
	AuditLogResponse
*/
package go_micro_srv_config_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_os_config "github.com/micro/go-os/config/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Change struct {
	Id        string                        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Path      string                        `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Author    string                        `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Comment   string                        `protobuf:"bytes,4,opt,name=comment" json:"comment,omitempty"`
	Timestamp int64                         `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	ChangeSet *go_micro_os_config.ChangeSet `protobuf:"bytes,6,opt,name=change_set,json=changeSet" json:"change_set,omitempty"`
}

func (m *Change) Reset()                    { *m = Change{} }
func (m *Change) String() string            { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()               {}
func (*Change) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Change) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Change) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Change) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Change) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Change) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Change) GetChangeSet() *go_micro_os_config.ChangeSet {
	if m != nil {
		return m.ChangeSet
	}
	return nil
}

type ChangeLog struct {
	Action string  `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Change *Change `protobuf:"bytes,2,opt,name=change" json:"change,omitempty"`
}

func (m *ChangeLog) Reset()                    { *m = ChangeLog{} }
func (m *ChangeLog) String() string            { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()               {}
func (*ChangeLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChangeLog) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ChangeLog) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type CreateRequest struct {
	Change *Change `protobuf:"bytes,1,opt,name=change" json:"change,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UpdateRequest struct {
	Change *Change `protobuf:"bytes,1,opt,name=change" json:"change,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteRequest struct {
	Change *Change `protobuf:"bytes,1,opt,name=change" json:"change,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ReadRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ReadResponse struct {
	Change *Change `protobuf:"bytes,1,opt,name=change" json:"change,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReadResponse) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type SearchRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Configs []*Change `protobuf:"bytes,1,rep,name=configs" json:"configs,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetConfigs() []*Change {
	if m != nil {
		return m.Configs
	}
	return nil
}

type WatchRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *WatchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WatchResponse struct {
	Id        string                        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ChangeSet *go_micro_os_config.ChangeSet `protobuf:"bytes,2,opt,name=change_set,json=changeSet" json:"change_set,omitempty"`
}

func (m *WatchResponse) Reset()                    { *m = WatchResponse{} }
func (m *WatchResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchResponse) ProtoMessage()               {}
func (*WatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *WatchResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WatchResponse) GetChangeSet() *go_micro_os_config.ChangeSet {
	if m != nil {
		return m.ChangeSet
	}
	return nil
}

type AuditLogRequest struct {
	// from unix timestamp
	From int64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	// to unix timestamp
	To int64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	// limit number items
	Limit int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	// the offset
	Offset int64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	// reverse the order
	Reverse bool `protobuf:"varint,5,opt,name=reverse" json:"reverse,omitempty"`
}

func (m *AuditLogRequest) Reset()                    { *m = AuditLogRequest{} }
func (m *AuditLogRequest) String() string            { return proto.CompactTextString(m) }
func (*AuditLogRequest) ProtoMessage()               {}
func (*AuditLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AuditLogRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *AuditLogRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *AuditLogRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AuditLogRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AuditLogRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type AuditLogResponse struct {
	Changes []*ChangeLog `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
}

func (m *AuditLogResponse) Reset()                    { *m = AuditLogResponse{} }
func (m *AuditLogResponse) String() string            { return proto.CompactTextString(m) }
func (*AuditLogResponse) ProtoMessage()               {}
func (*AuditLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AuditLogResponse) GetChanges() []*ChangeLog {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto.RegisterType((*Change)(nil), "go.micro.srv.config.config.Change")
	proto.RegisterType((*ChangeLog)(nil), "go.micro.srv.config.config.ChangeLog")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.config.config.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.config.config.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.config.config.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.config.config.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.config.config.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.config.config.DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.config.config.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.config.config.ReadResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.config.config.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.config.config.SearchResponse")
	proto.RegisterType((*WatchRequest)(nil), "go.micro.srv.config.config.WatchRequest")
	proto.RegisterType((*WatchResponse)(nil), "go.micro.srv.config.config.WatchResponse")
	proto.RegisterType((*AuditLogRequest)(nil), "go.micro.srv.config.config.AuditLogRequest")
	proto.RegisterType((*AuditLogResponse)(nil), "go.micro.srv.config.config.AuditLogResponse")
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0xc4, 0x6d, 0x26, 0x4d, 0xa8, 0x16, 0x84, 0x2c, 0x0b, 0x50, 0x64, 0x09, 0x91,
	0xf2, 0xe1, 0x94, 0x70, 0x43, 0x95, 0x10, 0x0a, 0x27, 0xa8, 0x38, 0x38, 0x42, 0x1c, 0x10, 0x2a,
	0xae, 0xb3, 0x71, 0x2c, 0xd5, 0xd9, 0xe0, 0xdd, 0xf4, 0xc6, 0x1f, 0x43, 0xfc, 0x38, 0xe4, 0xd9,
	0xdd, 0x24, 0x8e, 0x94, 0xad, 0xa3, 0xf6, 0x94, 0x9d, 0xd9, 0x99, 0xf7, 0xde, 0xac, 0xe6, 0x39,
	0xf0, 0x30, 0x61, 0xf3, 0x69, 0x96, 0x0e, 0xe4, 0x4f, 0xb8, 0x28, 0x98, 0x60, 0xc4, 0x4f, 0x59,
	0x98, 0x67, 0x49, 0xc1, 0x42, 0x5e, 0xdc, 0x84, 0xea, 0x4a, 0xfe, 0xf8, 0x67, 0x69, 0x26, 0x66,
	0xcb, 0xab, 0x30, 0x61, 0xf9, 0x00, 0x6b, 0x06, 0x29, 0x7b, 0xc3, 0xb8, 0x02, 0x18, 0x20, 0x40,
	0x05, 0x2d, 0xf8, 0x6b, 0x81, 0x3b, 0x9a, 0xc5, 0xf3, 0x94, 0x92, 0x2e, 0xd8, 0xd9, 0xc4, 0xb3,
	0x7a, 0x56, 0xbf, 0x15, 0xd9, 0xd9, 0x84, 0x10, 0x68, 0x2c, 0x62, 0x31, 0xf3, 0x6c, 0xcc, 0xe0,
	0x99, 0x3c, 0x06, 0x37, 0x5e, 0x8a, 0x19, 0x2b, 0x3c, 0x07, 0xb3, 0x2a, 0x22, 0x1e, 0x1c, 0x26,
	0x2c, 0xcf, 0xe9, 0x5c, 0x78, 0x0d, 0xbc, 0xd0, 0x21, 0x79, 0x02, 0x2d, 0x91, 0xe5, 0x94, 0x8b,
	0x38, 0x5f, 0x78, 0xcd, 0x9e, 0xd5, 0x77, 0xa2, 0x75, 0x82, 0x9c, 0x03, 0x24, 0xc8, 0x7e, 0xc9,
	0xa9, 0xf0, 0xdc, 0x9e, 0xd5, 0x6f, 0x0f, 0x9f, 0x86, 0xab, 0x09, 0x19, 0xd7, 0x03, 0x4a, 0x8d,
	0x63, 0x2a, 0xa2, 0x56, 0xa2, 0x8f, 0xc1, 0x25, 0xb4, 0x64, 0xfe, 0x82, 0xa5, 0x28, 0x2d, 0x11,
	0x19, 0x9b, 0xab, 0x11, 0x54, 0x44, 0xde, 0x83, 0x2b, 0x3b, 0x70, 0x90, 0xf6, 0x30, 0x08, 0x77,
	0x3f, 0xa0, 0xa2, 0x89, 0x54, 0x47, 0xf0, 0x05, 0x3a, 0xa3, 0x82, 0xc6, 0x82, 0x46, 0xf4, 0xf7,
	0x92, 0x72, 0xb1, 0x01, 0x66, 0xed, 0x0d, 0x76, 0x02, 0x5d, 0x0d, 0xc6, 0x17, 0x6c, 0xce, 0x11,
	0xfe, 0xdb, 0x62, 0x72, 0x7f, 0xf0, 0x1a, 0x6c, 0x0d, 0xff, 0x89, 0x5e, 0xd3, 0x7b, 0x83, 0xd7,
	0x60, 0x0a, 0xfe, 0x2d, 0xb4, 0x23, 0x1a, 0x4f, 0x34, 0x78, 0x8d, 0xf5, 0x09, 0x3e, 0xc3, 0xb1,
	0x6c, 0x91, 0x10, 0x77, 0x12, 0x44, 0xa1, 0x33, 0xa6, 0x71, 0x91, 0xcc, 0x76, 0x09, 0x58, 0xef,
	0xaa, 0x5d, 0xd9, 0xd5, 0x47, 0xd0, 0xbc, 0xce, 0xf2, 0x4c, 0xe0, 0x0a, 0x3b, 0x91, 0x0c, 0xca,
	0x6a, 0x36, 0x9d, 0x96, 0x5b, 0xd8, 0xc0, 0xb4, 0x8a, 0x82, 0xaf, 0xd0, 0xd5, 0x34, 0x4a, 0xf4,
	0x79, 0xb9, 0xeb, 0xa5, 0x22, 0xee, 0x59, 0x3d, 0xa7, 0xa6, 0x6a, 0xdd, 0x12, 0x3c, 0x83, 0xe3,
	0xef, 0xb1, 0xd8, 0xa9, 0x3a, 0xf8, 0x09, 0x1d, 0x75, 0xaf, 0xe8, 0xb6, 0xc7, 0xaa, 0x5a, 0xc6,
	0xde, 0xd3, 0x32, 0x7f, 0xe0, 0xc1, 0xc7, 0xe5, 0x24, 0x13, 0x17, 0x2c, 0xd5, 0x0a, 0x08, 0x34,
	0xa6, 0x05, 0xcb, 0x91, 0xc2, 0x89, 0xf0, 0x5c, 0x92, 0x0a, 0x86, 0xe0, 0x4e, 0x64, 0x0b, 0xb6,
	0xdf, 0x9b, 0x95, 0x5f, 0x83, 0x82, 0xde, 0xd0, 0x82, 0x53, 0x74, 0xfc, 0x51, 0xa4, 0xc3, 0x60,
	0x0c, 0x27, 0x6b, 0x7a, 0x35, 0xe0, 0x07, 0x38, 0x94, 0xfa, 0xf4, 0x7b, 0x3e, 0xbf, 0xfd, 0x3d,
	0xcb, 0x7e, 0xdd, 0x35, 0xfc, 0xd7, 0x04, 0x77, 0x84, 0xb7, 0x24, 0x06, 0x57, 0x7a, 0x8c, 0x9c,
	0x1a, 0x41, 0x36, 0x4d, 0xed, 0xbf, 0xac, 0x53, 0xaa, 0x96, 0xfe, 0xa0, 0xa4, 0x90, 0x3e, 0x33,
	0x53, 0x54, 0x8c, 0x6d, 0xa6, 0xd8, 0xb2, 0x2d, 0x52, 0x48, 0xaf, 0x99, 0x29, 0x2a, 0xe6, 0x36,
	0x53, 0x6c, 0x59, 0x17, 0x29, 0xe4, 0x5a, 0x9b, 0x29, 0x2a, 0x0e, 0x33, 0x53, 0x54, 0x5d, 0x12,
	0x1c, 0x90, 0x1f, 0xd0, 0x28, 0xcd, 0x4e, 0x5e, 0x98, 0xba, 0x36, 0xbe, 0x20, 0x7e, 0xff, 0xf6,
	0xc2, 0x15, 0x78, 0x0a, 0x47, 0x7a, 0x91, 0xc8, 0x2b, 0x53, 0xdf, 0xd6, 0xb6, 0xfb, 0xaf, 0xeb,
	0x15, 0xaf, 0x88, 0x7e, 0x41, 0x13, 0xfd, 0x48, 0x8c, 0xea, 0x36, 0x2d, 0xed, 0x9f, 0xd6, 0xa8,
	0xd4, 0xf8, 0x67, 0xd6, 0x95, 0x8b, 0xff, 0xc4, 0xef, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x47,
	0x21, 0x36, 0x21, 0xee, 0x07, 0x00, 0x00,
}
